<?php

require_once(get_stylesheet_directory()."/modules/vc/base-container.php");
require_once(get_stylesheet_directory()."/modules/vc/title-element.php");
require_once(get_stylesheet_directory()."/modules/vc/latest-posts.php");
require_once(get_stylesheet_directory()."/modules/vc/easy-button.php");
require_once(get_stylesheet_directory()."/modules/vc/separator.php");
require_once(get_stylesheet_directory()."/modules/vc/single-image.php");
require_once(get_stylesheet_directory()."/modules/vc/slick-carousel.php");
require_once(get_stylesheet_directory()."/modules/vc/cf7-newsletter.php");
require_once(get_stylesheet_directory()."/modules/vc/socials.php");
require_once(get_stylesheet_directory()."/modules/vc/list-element.php");
require_once(get_stylesheet_directory()."/modules/vc/text-rectangle.php");
require_once(get_stylesheet_directory()."/modules/vc/quote-block.php");
require_once(get_stylesheet_directory()."/modules/vc/text-block.php");
require_once(get_stylesheet_directory()."/modules/vc/feature-icon.php");
require_once(get_stylesheet_directory()."/modules/vc/company-data.php");
require_once(get_stylesheet_directory()."/modules/vc/cf7-contact-form.php");
require_once(get_stylesheet_directory()."/modules/vc/content-block.php");
require_once(get_stylesheet_directory()."/modules/vc/slider.php");
